# Generated by LocalLearn AI
# Topic: insertion sort
# Model: llama3:latest
#
# Output directory: output\insertion_sort_20261006_235858
# Re-generate: python generate.py "insertion sort"

from manim import *


class LocalLearnScene(Scene):

    # Generated by LocalLearn AI
    # Topic: insertion_sort
    # Language: hi

    def construct(self):

        # --- Scene 1: title ---
        _title = Text('insertion_sort है', font_size=52)
        self.play(Write(_title), run_time=1)
        self.wait(2.0)
        self.play(FadeOut(_title), run_time=0.5)

        # --- Scene 2: definition ---
        _hd = Text('Definition', font_size=36)
        _hd.to_edge(UP, buff=0.35)
        self.play(Write(_hd), run_time=0.8)
        _body = Text('एक element एक बार एक सॉर्टेड array बनाता है', font_size=28)
        _body.move_to(ORIGIN)
        self.play(FadeIn(_body, shift=UP*0.2), run_time=0.8)
        self.wait(3.5)
        self.play(FadeOut(VGroup(_hd, _body)), run_time=0.5)


        # --- Scene 3: explanation ---
        _hd = Text('insertion sort के द्वारा एक element एक सॉर्टेड array में जोड़ा जाता है', font_size=36)
        _hd.to_edge(UP, buff=0.35)
        self.play(Write(_hd), run_time=0.8)
        _pts = VGroup()
        _pts.add(Text('• element को correct position में जोड़ा जाता है', font_size=26))
        _pts.add(Text('• अन्य elements को नहीं बदला जाता है', font_size=26))
        _pts.arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _pts.move_to(ORIGIN)
        self.play(FadeIn(_pts[0], shift=RIGHT*0.2), run_time=0.6)
        self.play(FadeIn(_pts[1], shift=RIGHT*0.2), run_time=0.6)
        self.wait(4.5)
        self.play(FadeOut(VGroup(_hd, _pts)), run_time=0.5)

        # --- Scene 4: array_sort (bubble sort) ---
        _sort_vals = ['5, 2, 8, 3, 1, 6, 4']
        _svals = list(_sort_vals)

        _hd = Text('बबल सॉर्ट', font_size=36)
        _hd.to_edge(UP, buff=0.35)
        self.play(Write(_hd), run_time=0.8)

        def _make_cells(vals):
            cells = VGroup()
            for v in vals:
                box = Square(side_length=0.85, stroke_width=2.5)
                lbl = Text(str(v), font_size=26)
                lbl.move_to(box.get_center())
                cells.add(VGroup(box, lbl))
            cells.arrange(RIGHT, buff=0.12)
            cells.move_to(ORIGIN)
            return cells

        _cells = _make_cells(_svals)
        self.play(LaggedStart(
            *[FadeIn(c, shift=UP*0.15) for c in _cells],
            lag_ratio=0.1), run_time=1.0)
        self.wait(0.5)

        # Bubble sort passes (up to 3 passes shown)
        _passes = 0
        for _pass in range(len(_svals) - 1):
            if _passes >= 3:
                break
            _swapped = False
            for _j in range(len(_svals) - 1 - _pass):
                if _svals[_j] > _svals[_j + 1]:
                    _svals[_j], _svals[_j + 1] = _svals[_j + 1], _svals[_j]
                    _swapped = True
                    _new = _make_cells(_svals)
                    self.play(ReplacementTransform(_cells, _new), run_time=0.5)
                    _cells = _new
            if not _swapped:
                break
            _passes += 1

        _done = Text('क्रमबद्ध!', font_size=32, color=GREEN)
        _done.to_edge(DOWN, buff=0.5)
        self.play(Write(_done), run_time=0.6)
        self.wait(1.5)
        self.play(FadeOut(VGroup(_hd, _cells, _done)), run_time=0.6)

        # --- Scene 5: complexity ---
        _cx_hd  = Text('insertion sort की सटीकता O(n^2) है', font_size=34)
        _cx_hd.to_edge(UP, buff=0.8)
        _cx_val = Text('O(n^2)', font_size=64)
        _cx_val.move_to(ORIGIN)
        self.play(Write(_cx_hd), run_time=0.8)
        self.play(Write(_cx_val), run_time=1.0)
        self.wait(4.5)
        self.play(FadeOut(VGroup(_cx_hd, _cx_val)), run_time=0.5)


        # --- Scene 6: summary ---
        _sm_hd = Text('insertion sort एक efficient sorting algorithm है', font_size=36)
        _sm_hd.to_edge(UP, buff=0.35)
        self.play(Write(_sm_hd), run_time=0.8)
        _sm_pts = VGroup()
        _sm_pts.add(Text('• correctly sorts arrays', font_size=26))
        _sm_pts.add(Text('• simple to implement', font_size=26))
        _sm_pts.arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _sm_pts.move_to(ORIGIN)
        self.play(FadeIn(_sm_pts[0], shift=RIGHT*0.2), run_time=0.5)
        self.play(FadeIn(_sm_pts[1], shift=RIGHT*0.2), run_time=0.5)
        self.wait(4.9)
        self.play(FadeOut(VGroup(_sm_hd, _sm_pts)), run_time=0.5)

        # --- Outro ---
        _outro = Text('LocalLearn AI', font_size=48)
        _outro_sub = Text('सीखें  ·  देखें  ·  समझें', font_size=26)
        _outro_sub.next_to(_outro, DOWN, buff=0.3)
        self.play(Write(_outro), run_time=1.0)
        self.play(FadeIn(_outro_sub), run_time=0.8)
        self.wait(3)

