# Generated by LocalLearn AI (Two-Stage System)
# Topic: Explain Bubble Sort
# Model: llama3:latest
# Stage 1: Lesson planning
# Stage 2: Manim code generation
#
# Render: python render.py generated_scene.py LocalLearnScene --low
# Re-generate: python generate.py "Explain Bubble Sort"

from manim import *

class LocalLearnScene(Scene):
    def construct(self):
        self.add_title()
        self.explain_concept()
        self.visualize_process()
        self.show_concrete_example()
        self.demonstrate_step_by_step()
        self.highlight_comparison()
        self.continue_process()
        self.show_result()
        self.provide_key_insight()
        self.analyze_complexity()

    def add_title(self):
        title = Text("Bubble Sort", font_size=44, font="Arial").center()
        subtitle = Text("A Simple Sorting Algorithm", font_size=32, font="Arial").next_to(title, DOWN)
        self.play(Write(title), Write(subtitle))
        self.wait(2)

    def explain_concept(self):
        array = VGroup(*[Rectangle(width=0.5, height=0.2, fill_color=RGB(0.8, 0.8, 0.8)) for _ in range(5)]).arrange(RIGHT, buff=0.2)
        self.play(FadeIn(array))
        self.wait(2)

    def visualize_process(self):
        array = VGroup(*[Rectangle(width=0.5, height=0.2, fill_color=RGB(0.8, 0.8, 0.8)) for _ in range(5)]).arrange(RIGHT, buff=0.2)
        self.play(FadeIn(array))
        self.wait(2)

    def show_concrete_example(self):
        array = VGroup(*[Rectangle(width=0.5, height=0.2, fill_color=RGB(0.8, 0.8, 0.8)) for _ in range(5)]).arrange(RIGHT, buff=0.2)
        self.play(FadeIn(array))
        self.wait(2)

    def demonstrate_step_by_step(self):
        array = VGroup(*[Rectangle(width=0.5, height=0.2, fill_color=RGB(0.8, 0.8, 0.8)) for _ in range(5)]).arrange(RIGHT, buff=0.2)
        self.play(FadeIn(array))
        self.wait(2)

    def highlight_comparison(self):
        array = VGroup(*[Rectangle(width=0.5, height=0.2, fill_color=RGB(0.8, 0.8, 0.8)) for _ in range(5)]).arrange(RIGHT, buff=0.2)
        self.play(FadeIn(array))
        self.wait(2)

    def continue_process(self):
        array = VGroup(*[Rectangle(width=0.5, height=0.2, fill_color=RGB(0.8, 0.8, 0.8)) for _ in range(5)]).arrange(RIGHT, buff=0.2)
        self.play(FadeIn(array))
        self.wait(2)

    def show_result(self):
        array = VGroup(*[Rectangle(width=0.5, height=0.2, fill_color=RGB(0.8, 0.8, 0.8)) for _ in range(5)]).arrange(RIGHT, buff=0.2)
        self.play(FadeIn(array))
        self.wait(2)

    def provide_key_insight(self):
        array = VGroup(*[Rectangle(width=0.5, height=0.2, fill_color=RGB(0.8, 0.8, 0.8)) for _ in range(5)]).arrange(RIGHT, buff=0.2)
        self.play(FadeIn(array))
        self.wait(2)

    def analyze_complexity(self):
        array = VGroup(*[Rectangle(width=0.5, height=0.2, fill_color=RGB(0.8, 0.8, 0.8)) for _ in range(5)]).arrange(RIGHT, buff=0.2)
        self.play(FadeIn(array))
        self.wait(2)
