# Generated by LocalLearn AI
# Topic : Explain Bubble Sort
# Model : llama3:latest
# Render: manim generated_scene.py LocalLearnScene
#
# Re-generate with: python generate.py "Explain Bubble Sort"

from manim import *

class LocalLearnScene(Scene):
    def construct(self):
        title = Text("Bubble Sort", font_size=44, font="Arial")
        self.play(FadeIn(title), run_time=2)
        self.wait()

        heading = Text("How it works", font_size=36, font="Arial")
        heading.to_edge(DOWN, buff=0.2)
        self.play(Write(heading), run_time=1)
        self.wait()

        bubble_sort = VGroup(
            Text("1. Compare adjacent elements", font_size=28, font="Arial"),
            Text("2. If out of order, swap them", font_size=28, font="Arial"),
            Text("3. Repeat until no more swaps needed", font_size=28, font="Arial"),
        )
        bubble_sort.arrange(RIGHT, buff=0.2)
        bubble_sort.to_edge(DOWN, buff=0.5)
        self.play(Write(bubble_sort), run_time=2)
        self.wait()

        array = VGroup(
            Text("5", font_size=24, font="Arial"),
            Text("2", font_size=24, font="Arial"),
            Text("8", font_size=24, font="Arial"),
            Text("3", font_size=24, font="Arial"),
            Text("1", font_size=24, font="Arial"),
            Text("6", font_size=24, font="Arial"),
            Text("4", font_size=24, font="Arial"),
        )
        array.arrange(RIGHT, buff=0.2)
        array.to_edge(DOWN, buff=0.5)
        self.play(Write(array), run_time=2)
        self.wait()

        arrow = Arrow(start=DOWN, end=UP, stroke_width=2, color=WHITE)
        arrow.next_to(array, RIGHT, buff=0.2)
        self.play(FadeIn(arrow), run_time=1)
        self.wait()

        swapped = VGroup(
            Text("Swap 5 and 2", font_size=24, font="Arial"),
            Text("Swap 8 and 3", font_size=24, font="Arial"),
            Text("Swap 1 and 6", font_size=24, font="Arial"),
        )
        swapped.arrange(RIGHT, buff=0.2)
        swapped.to_edge(DOWN, buff=0.5)
        self.play(Write(swapped), run_time=2)
        self.wait()

        self.play(FadeOut(title), FadeOut(heading), FadeOut(bubble_sort), FadeOut(array), FadeOut(arrow), FadeOut(swapped), run_time=2)
        self.wait()
