"""
LocalLearn AI - Generation Orchestrator
-----------------------------------------
Usage:
    python generate.py "Explain Binary Search"

Architecture:
    ONE compact Ollama call  →  compact JSON LessonSpec
    Deterministic Python     →  Manim code (no LLM needed)
    Validation               →  syntax + structure + API scan
    Save                     →  generated_scene.py

Render manually:
    python render.py generated_scene.py LocalLearnScene --low
"""

import sys
import os
import time
import json

from lesson_planner import generate_lesson_plan
from scene_builder  import build_manim_code
from validator      import validate_and_estimate

MODEL            = "llama3:latest"
OUTPUT_FILE      = "generated_scene.py"
LESSON_SPEC_FILE = "lesson_spec.json"
INVALID_FILE     = "generated_scene_invalid.py"

SEP = "  " + "-" * 43

# ---------------------------------------------------------------------------
# FILE HELPERS
# ---------------------------------------------------------------------------

def _save_json(spec: dict, path: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(spec, fh, indent=2)


def _save_code(path: str, topic: str, code: str) -> None:
    header = (
        f"# Generated by LocalLearn AI\n"
        f"# Topic: {topic}\n"
        f"# Model: {MODEL}\n"
        f"#\n"
        f"# Render: python render.py {OUTPUT_FILE} LocalLearnScene --low\n"
        f"# Re-generate: python generate.py \"{topic}\"\n\n"
    )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(header + code + "\n")


def _existing_is_valid() -> bool:
    if not os.path.exists(OUTPUT_FILE):
        return False
    with open(OUTPUT_FILE, "r", encoding="utf-8") as fh:
        existing = fh.read()
    return validate_and_estimate(existing)["is_valid"]

# ---------------------------------------------------------------------------
# SYNTAX REPAIR (one attempt via Ollama — only if needed)
# ---------------------------------------------------------------------------

def _attempt_repair(code: str, syntax_err) -> tuple:
    """One Ollama repair attempt. Returns (repaired_code|None, elapsed)."""
    import urllib.request

    err_msg  = syntax_err.msg    if hasattr(syntax_err, "msg")    else str(syntax_err)
    err_line = syntax_err.lineno if hasattr(syntax_err, "lineno") else "?"

    print(f"  Attempting syntax repair (line {err_line}: {err_msg})...")

    prompt = (
        "Fix the Python syntax error in this Manim code.\n"
        "Do NOT redesign the animation. Fix ONLY the syntax error.\n"
        "Return the complete corrected Python code. No Markdown.\n"
        f"\nSyntax error: {err_msg}\nLine: {err_line}\n\nCode:\n{code}\n"
    )
    payload = {
        "model": MODEL, "prompt": prompt, "stream": False,
        "options": {"num_predict": 1500, "temperature": 0.1},
    }
    body = json.dumps(payload).encode("utf-8")
    req  = urllib.request.Request(
        "http://localhost:11434/api/generate", data=body,
        headers={"Content-Type": "application/json"}, method="POST",
    )
    start = time.perf_counter()
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        raw = data.get("response", "")
    except Exception as exc:
        print(f"  Repair failed: {exc}")
        return None, time.perf_counter() - start
    elapsed = time.perf_counter() - start

    # Strip fences / preamble
    text = raw.strip()
    if "```" in text:
        lines, inside, out = text.splitlines(), False, []
        for ln in lines:
            if not inside:
                if ln.strip().startswith("```"):
                    inside = True
            else:
                if ln.strip() == "```":
                    break
                out.append(ln)
        if out:
            text = "\n".join(out).strip()
    lns = text.splitlines()
    for i, ln in enumerate(lns):
        s = ln.strip()
        if s.startswith("from manim import") or s.startswith("import manim"):
            text = "\n".join(lns[i:]).strip()
            break

    return (text if text else None), elapsed

# ---------------------------------------------------------------------------
# DISPLAY
# ---------------------------------------------------------------------------

def _banner(topic: str) -> None:
    print()
    print(SEP)
    print("  LocalLearn AI")
    print(SEP)
    print(f"  Topic: {topic}")
    print(f"  Model: {MODEL}")
    print(SEP)
    print()


def _print_validation(result: dict, val_time: float) -> None:
    print("  Validating...")
    if result["syntax_valid"]:
        print("  Syntax:    PASS")
    else:
        err = result["syntax_error"]
        ln  = err.lineno if hasattr(err, "lineno") else "?"
        print(f"  Syntax:    FAIL  (line {ln}: {err.msg if hasattr(err,'msg') else err})")
    print("  Structure: " + ("PASS" if not result["structure_errors"] else "FAIL"))
    api_w = result.get("api_warnings", [])
    if not api_w:
        print("  API scan:  PASS")
    else:
        print(f"  API scan:  WARN  ({len(api_w)} issue(s))")
        for w in api_w:
            print(f"    {w['label']}")
            for lineno, src in w["lines"][:2]:
                print(f"      Line {lineno}: {src}")
    print(f"  Val time:  {val_time:.2f} sec")
    print()


def _print_summary(
    topic: str,
    conn_time: float,
    planning_time: float,
    build_time: float,
    val_time: float,
    result: dict,
    total_time: float,
    repair_time: float = 0.0,
    failed: bool = False,
) -> None:
    print()
    print(SEP)
    print("  LocalLearn AI")
    print(SEP)
    print(f"  Topic: {topic}")
    print(f"  Model: {MODEL}")
    print(SEP)
    print(f"  Ollama connection:  {conn_time:.2f} sec")
    print(f"  Lesson planning:    {planning_time:.2f} sec")
    print(f"  Code generation:    {build_time:.4f} sec  (deterministic)")
    if repair_time > 0:
        print(f"  Repair:             {repair_time:.2f} sec")
    print(f"  Validation:         {val_time:.2f} sec")
    if result.get("syntax_valid"):
        dur = result["estimated_duration"]
        cls = result["duration_classification"]
        print(f"  Estimated duration: {dur:.1f} sec  [{cls}]")
    print(SEP)
    print()
    if failed:
        print("  GENERATION FAILED.")
        print("  LocalLearn could not produce valid Manim code.")
    else:
        print("  Generated successfully.")
        print()
        print("  Saved:")
        print(f"    {OUTPUT_FILE}")
        print()
        print("  To render (low quality):")
        print(f"    python render.py {OUTPUT_FILE} LocalLearnScene --low")
        print()
        print("  To render (full quality):")
        print(f"    python render.py {OUTPUT_FILE} LocalLearnScene --high")
    print()

# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main() -> None:

    pipeline_start = time.perf_counter()

    if len(sys.argv) < 2 or not sys.argv[1].strip():
        print()
        print("  Usage:   python generate.py \"<topic>\"")
        print("  Example: python generate.py \"Explain Binary Search\"")
        print()
        sys.exit(1)

    topic = sys.argv[1].strip()
    _banner(topic)

    # ------------------------------------------------------------------
    # STAGE 1 — compact Ollama call for lesson spec
    # ------------------------------------------------------------------
    print("  Connecting to Ollama...")
    conn_start = time.perf_counter()

    try:
        lesson_spec, planning_time = generate_lesson_plan(topic)
    except RuntimeError as exc:
        print(f"\n  [ERROR] {exc}")
        sys.exit(1)
    except TimeoutError as exc:
        print(f"\n  [TIMEOUT] {exc}")
        sys.exit(1)
    except ValueError as exc:
        print(f"\n  [ERROR] {exc}")
        sys.exit(1)

    # conn_time = wall-clock from "Connecting..." to response received
    conn_time = time.perf_counter() - conn_start

    print("  Ollama connection successful.")
    print(f"  Connection time:  {conn_time:.2f} sec")
    print()
    print("  Lesson plan generated.")
    print(f"  Planning time:    {planning_time:.2f} sec")
    print(f"  Scenes:           {len(lesson_spec.get('scenes', []))}")
    print(f"  Target duration:  {lesson_spec.get('target_duration', 75)} sec")
    print()

    _save_json(lesson_spec, LESSON_SPEC_FILE)
    print(f"  Lesson plan saved: {LESSON_SPEC_FILE}")
    print()

    # ------------------------------------------------------------------
    # STAGE 2 — deterministic Python code generation (no LLM)
    # ------------------------------------------------------------------
    print("  Building Manim code (deterministic)...")
    build_start = time.perf_counter()
    code        = build_manim_code(lesson_spec)
    build_time  = time.perf_counter() - build_start
    print(f"  Code built in {build_time:.4f} sec")
    print()

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------
    val_start = time.perf_counter()
    result    = validate_and_estimate(code)
    val_time  = time.perf_counter() - val_start

    _print_validation(result, val_time)

    repair_time = 0.0

    # Handle syntax errors (should be rare — code is deterministic)
    if not result["syntax_valid"]:
        repaired, repair_time = _attempt_repair(code, result["syntax_error"])
        if repaired:
            result = validate_and_estimate(repaired)
            if result["syntax_valid"]:
                print("  Syntax:    PASS  (after repair)")
                code = repaired
            else:
                print("  Syntax:    FAIL  (repair did not fix it)")
        else:
            print("  Repair failed.")

        if not result["syntax_valid"]:
            _save_code(INVALID_FILE, topic, code)
            print(f"  Invalid code saved: {INVALID_FILE}")
            if _existing_is_valid():
                print(f"  Existing '{OUTPUT_FILE}' was NOT overwritten.")
            total = time.perf_counter() - pipeline_start
            _print_summary(topic, conn_time, planning_time, build_time,
                           val_time, result, total, repair_time, failed=True)
            sys.exit(1)

    # Handle API warnings with a pre-render repair
    api_warnings = result.get("api_warnings", [])
    if api_warnings:
        print("  API warnings detected — attempting pre-render repair...")
        first_warn  = api_warnings[0]
        first_match = first_warn["lines"][0] if first_warn["lines"] else (0, "")
        lineno, src = first_match
        all_labels  = "; ".join(w["label"] for w in api_warnings)

        error_info = {
            "error_type":  "APIWarning",
            "error_msg":   all_labels,
            "error_line":  lineno,
            "source_line": src,
        }
        from manim_repair import repair_manim_code
        repaired, api_rt = repair_manim_code(code, error_info, attempt_number=1)
        repair_time += api_rt

        if repaired:
            new_result = validate_and_estimate(repaired)
            remaining  = new_result.get("api_warnings", [])
            if not remaining:
                print("  API scan:  PASS  (after repair)")
            else:
                print(f"  API scan:  WARN  ({len(remaining)} issue(s) remain — proceeding)")
            code   = repaired
            result = new_result
        else:
            print("  Pre-render repair failed — proceeding anyway")
        print()

    # ------------------------------------------------------------------
    # Save
    # ------------------------------------------------------------------
    _save_code(OUTPUT_FILE, topic, code)

    total_time = time.perf_counter() - pipeline_start
    _print_summary(topic, conn_time, planning_time, build_time,
                   val_time, result, total_time, repair_time)


if __name__ == "__main__":
    main()
