"""
LocalLearn AI - Full Pipeline (One Command)
--------------------------------------------
Usage:
    python generate.py "insertion sort"
    python generate.py "insertion sort" --language hi
    python generate.py "binary search" --language ta

Supported language codes:
    en  English (default)
    hi  Hindi
    ta  Tamil
    te  Telugu
    mr  Marathi

NEW ARCHITECTURE - 7-Stage Pipeline:
    [1/7] Lesson Planning (Ollama) - structured beats with visual plans
    [2/7] TTS Generation - native audio for each beat's narration
    [3/7] Audio Timing - measure actual durations for sync
    [4/7] Scene Generation - deterministic Manim scene from visual plans
    [5/7] Manim Rendering - silent video with algorithm animations
    [6/7] Audio+Video Muxing - FFmpeg combines for final output
    [7/7] Complete - professional quality educational video

Output is organised under:
    output/<safe_topic>_<timestamp>/
        lesson_spec.json         - planning output (beats + visual plans)
        audio_output/            - TTS-generated audio files per beat
        generated_scene.py       - Manim scene file
        silent_video.mp4         - Manim output (no audio)
        final_video.mp4          - FINAL OUTPUT (with audio)
"""

import sys
import os
import re
import time
import json
import glob
import shutil
import subprocess
import datetime
from pathlib import Path

from lesson_planner import generate_lesson_plan
from visual_renderer import create_visual_renderer
from muxing_service import create_muxing_service
from language_codes import (
    LanguageCode,
    DEFAULT_LANGUAGE,
    LANGUAGE_NAMES,
    validate_language,
)

# ---------------------------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------------------------

MODEL         = "llama3:latest"
SCENE_CLASS   = "GeneratedLessonScene"
QUALITY_FLAG  = "-ql"   # low quality = fast; use -qm/-qh for better quality
OUTPUT_ROOT   = "output"
MANIM_TIMEOUT = 600     # 10 minutes for Manim rendering
TTS_TIMEOUT   = 120     # 2 minutes for TTS generation (Piper is fast)

# TTS now uses Piper (lightweight) in the main .venv
# No need for separate .tts-venv anymore
_HERE       = os.path.dirname(os.path.abspath(__file__))
TTS_PYTHON  = sys.executable  # Use same Python as main process
TTS_WORKER  = os.path.join(_HERE, "tts_worker.py")

SEP = "  " + "-" * 70

# ---------------------------------------------------------------------------
# FILESYSTEM HELPERS
# ---------------------------------------------------------------------------

def _safe_name(topic: str) -> str:
    """Convert a topic string into a safe directory name."""
    name = topic.lower().strip()
    name = re.sub(r"[^\w\s-]", "", name)        # remove punctuation
    name = re.sub(r"[\s_-]+", "_", name)         # collapse spaces/dashes
    name = name.strip("_")
    return name[:60]                              # cap at 60 chars


def _make_run_dir(topic: str) -> str:
    """
    Create a unique output directory for this run.

    Format:  output/<safe_topic>_<YYYYMMDD_HHMMSS>/
    """
    ts      = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    dirname = f"{_safe_name(topic)}_{ts}"
    path    = os.path.join(OUTPUT_ROOT, dirname)
    os.makedirs(path, exist_ok=True)
    return path


def _save_json(spec: dict, path: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(spec, fh, indent=2)


def _save_code(path: str, topic: str, run_dir: str, code: str) -> None:
    scene_file = os.path.basename(path)
    header = (
        f"# Generated by LocalLearn AI\n"
        f"# Topic: {topic}\n"
        f"# Model: {MODEL}\n"
        f"#\n"
        f"# Output directory: {run_dir}\n"
        f"# Re-generate: python generate.py \"{topic}\"\n\n"
    )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(header + code + "\n")

# ---------------------------------------------------------------------------
# TTS SUBPROCESS RUNNER
# ---------------------------------------------------------------------------

def _run_tts_subprocess(lesson_spec: dict, audio_dir: str) -> tuple:
    """
    Run TTS generation using Piper TTS by spawning tts_worker.py.

    Uses the main .venv (same Python as generate.py).
    Piper is lightweight and doesn't need separate venv.

    Communication:
        stdin  -> JSON job
        stdout <- JSON result (PURE JSON, no other text)
        stderr -> progress lines printed live to the terminal

    Returns:
        (enriched_beats: list[dict], metadata: dict)
    Raises:
        RuntimeError on any failure.
    """
    if not os.path.exists(TTS_WORKER):
        raise RuntimeError(f"tts_worker.py not found: {TTS_WORKER}")

    beats = lesson_spec.get("beats", [])
    job   = {
        "beats":      beats,
        "output_dir": audio_dir,
        "language":   lesson_spec.get("language", "en"),
    }

    print(f"  Spawning TTS worker (Piper TTS)...")
    print(f"  Processing {len(beats)} beats...")
    print()

    try:
        proc = subprocess.run(
            [TTS_PYTHON, TTS_WORKER],
            input=json.dumps(job),
            stdout=subprocess.PIPE,   # capture result JSON
            stderr=None,              # let stderr flow directly to terminal (live progress)
            text=True,
            timeout=TTS_TIMEOUT,
        )
    except subprocess.TimeoutExpired:
        raise RuntimeError(f"TTS worker timed out after {TTS_TIMEOUT}s")
    except FileNotFoundError:
        raise RuntimeError(f"Could not launch: {TTS_PYTHON}")

    stdout = (proc.stdout or "").strip()

    if not stdout:
        raise RuntimeError(
            "TTS worker produced no output.\n"
            "Check the progress messages above for error details."
        )

    try:
        response = json.loads(stdout)
    except json.JSONDecodeError as e:
        raise RuntimeError(
            f"TTS worker output was not valid JSON: {e}\n"
            f"stdout: {stdout[:300]}"
        )

    if not response.get("ok"):
        raise RuntimeError(f"TTS worker failed: {response.get('error', 'unknown')}")

    enriched_beats = response["enriched_beats"]
    metadata = {
        "total_duration": response["total_duration"],
        "beat_count":     response["beat_count"],
        "audio_files":    [b["audio_file"] for b in enriched_beats],
    }
    return enriched_beats, metadata


# ---------------------------------------------------------------------------
# MANIM RENDERER
# ---------------------------------------------------------------------------

def _render_manim(scene_file: str, scene_class: str, quality_flag: str, output_dir: str) -> tuple:
    """
    Invoke Manim via subprocess to render silent video.

    Returns:
        (success: bool, video_path: str|None, elapsed_seconds: float)
    """
    cmd = [
        sys.executable, "-m", "manim",
        quality_flag,
        scene_file,
        scene_class,
        "--output_file", "silent_video",
        "--media_dir", os.path.join(output_dir, "media"),
    ]

    start = time.perf_counter()

    try:
        print("  Running Manim...")
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=MANIM_TIMEOUT
        )
        
        elapsed = time.perf_counter() - start
        
        if result.returncode != 0:
            print(f"  [ERROR] Manim rendering failed:")
            print(result.stderr)
            return False, None, elapsed
        
        # Find the generated video
        video_path = _find_manim_output(output_dir, scene_file, scene_class)
        
        if not video_path:
            print("  [ERROR] Could not locate Manim output video")
            return False, None, elapsed
        
        return True, video_path, elapsed

    except subprocess.TimeoutExpired:
        elapsed = time.perf_counter() - start
        print(f"  [ERROR] Manim rendering timed out after {MANIM_TIMEOUT}s")
        return False, None, elapsed
    except FileNotFoundError:
        elapsed = time.perf_counter() - start
        print("  [ERROR] Manim not found. Install with: pip install manim")
        return False, None, elapsed
    except Exception as e:
        elapsed = time.perf_counter() - start
        print(f"  [ERROR] Manim rendering failed: {e}")
        return False, None, elapsed


def _find_manim_output(output_dir: str, scene_file: str, scene_class: str) -> str | None:
    """Find the Manim-generated video file."""
    # Manim outputs to media/videos/<scene_name>/<quality>/
    media_dir = os.path.join(output_dir, "media", "videos")
    
    if not os.path.exists(media_dir):
        return None
    
    # Search for MP4 files
    for root, dirs, files in os.walk(media_dir):
        for file in files:
            if file.endswith(".mp4"):
                return os.path.join(root, file)
    
    return None

# ---------------------------------------------------------------------------
# DISPLAY
# ---------------------------------------------------------------------------

def _banner(topic: str, language: LanguageCode) -> None:
    lang_display = LANGUAGE_NAMES[language]
    print()
    print(SEP)
    print("  LocalLearn AI - Professional Educational Video Generator")
    print(SEP)
    print(f"  Topic:    {topic}")
    print(f"  Language: {lang_display} ({language.value})")
    print(f"  Model:    {MODEL}")
    print(SEP)
    print()


def _step(n: int, total: int, label: str) -> None:
    print(f"  [{n}/{total}] {label}")
    print()


def _print_final_summary(
    topic: str,
    language: LanguageCode,
    stage_times: dict,
    total_time: float,
    video_path: str | None,
    video_duration: float | None,
    run_dir: str,
    failed: bool = False,
) -> None:
    lang_display = LANGUAGE_NAMES[language]
    print()
    print(SEP)
    if failed:
        print("  LOCALLEARN AI — FAILED")
    else:
        print("  LOCALLEARN AI COMPLETE ✓")
    print(SEP)
    print()
    print(f"  Topic:              {topic}")
    print(f"  Language:           {lang_display} ({language.value})")
    print()
    print("  Pipeline Timing:")
    print(f"    [1/7] Planning:     {stage_times.get('planning', 0):.2f}s")
    print(f"    [2/7] TTS:          {stage_times.get('tts', 0):.2f}s")
    print(f"    [3/7] Timing:       {stage_times.get('timing', 0):.2f}s")
    print(f"    [4/7] Scene Gen:    {stage_times.get('scene_gen', 0):.4f}s")
    print(f"    [5/7] Manim:        {stage_times.get('manim', 0):.2f}s")
    print(f"    [6/7] Muxing:       {stage_times.get('muxing', 0):.2f}s")
    print(f"    [7/7] Complete:     {stage_times.get('complete', 0):.2f}s")
    print()
    print(f"  Total Pipeline:     {total_time:.2f}s ({total_time/60:.1f} min)")
    print()

    if not failed and video_path:
        print(f"  FINAL VIDEO:")
        print(f"    {os.path.abspath(video_path)}")
        print()
        if video_duration:
            print(f"  Video Duration:     {video_duration:.1f}s")
        print()
        print(f"  Output Directory:")
        print(f"    {os.path.abspath(run_dir)}")
    elif failed:
        print("  Pipeline did not complete successfully.")
        print(f"  Partial output in: {os.path.abspath(run_dir)}")

    print()
    print(SEP)
    print()

# ---------------------------------------------------------------------------
# MAIN - 7-STAGE PIPELINE
# ---------------------------------------------------------------------------

def main() -> None:
    """
    Main entry point for LocalLearn AI video generation.
    
    Orchestrates the complete 7-stage pipeline:
    1. Lesson Planning (Ollama)
    2. TTS Generation
    3. Audio Timing Measurement
    4. Scene File Generation
    5. Manim Rendering (silent video)
    6. Audio+Video Muxing
    7. Complete
    """
    
    pipeline_start = time.perf_counter()
    stage_times = {}

    # Parse arguments
    args = sys.argv[1:]

    if not args or not args[0].strip():
        print()
        print("  Usage:   python generate.py \"<topic>\" [--language <code>]")
        print("  Example: python generate.py \"insertion sort\" --language hi")
        print()
        print("  Supported language codes:")
        for lc in LanguageCode:
            default_marker = "  (default)" if lc == DEFAULT_LANGUAGE else ""
            print(f"    {lc.value}  {LANGUAGE_NAMES[lc]}{default_marker}")
        print()
        sys.exit(1)

    topic = args[0].strip()

    # Parse optional --language flag
    language = DEFAULT_LANGUAGE
    if "--language" in args:
        lang_idx = args.index("--language")
        if lang_idx + 1 >= len(args):
            print("\n  [ERROR] --language requires a value, e.g. --language hi\n")
            sys.exit(1)
        lang_code = args[lang_idx + 1]
        try:
            language = validate_language(lang_code)
        except ValueError as exc:
            print(f"\n  [ERROR] {exc}\n")
            sys.exit(1)

    _banner(topic, language)

    # Create output directory structure
    run_dir = _make_run_dir(topic)
    audio_dir = os.path.join(run_dir, "audio_output")
    os.makedirs(audio_dir, exist_ok=True)

    spec_path = os.path.join(run_dir, "lesson_spec.json")
    scene_path = os.path.join(run_dir, "generated_scene.py")
    final_video_path = os.path.join(run_dir, "final_video.mp4")

    TOTAL_STAGES = 7

    try:
        # ===================================================================
        # STAGE 1: LESSON PLANNING (Ollama)
        # ===================================================================
        _step(1, TOTAL_STAGES, "Lesson Planning (Ollama)")
        
        stage_start = time.perf_counter()
        try:
            lesson_spec, planning_time = generate_lesson_plan(topic, language=language)
        except Exception as e:
            print(f"  [ERROR] Lesson planning failed: {e}")
            raise
        
        stage_times['planning'] = time.perf_counter() - stage_start
        
        # Save lesson spec
        _save_json(lesson_spec, spec_path)
        
        beats = lesson_spec.get("beats", [])
        target_dur = lesson_spec.get("target_duration", 90)
        
        print(f"  ✓ Lesson specification generated")
        print(f"    Planning time: {stage_times['planning']:.2f}s")
        print(f"    Beats: {len(beats)}")
        print(f"    Target duration: {target_dur}s")
        print(f"    Saved: {os.path.basename(spec_path)}")
        print()

        # ===================================================================
        # STAGE 2: TTS GENERATION
        # ===================================================================
        _step(2, TOTAL_STAGES, "TTS Generation")
        
        stage_start = time.perf_counter()
        
        try:
            enriched_beats, audio_metadata = _run_tts_subprocess(lesson_spec, audio_dir)
        except Exception as e:
            print(f"  [ERROR] TTS generation failed: {e}")
            raise
        
        stage_times['tts'] = time.perf_counter() - stage_start
        
        total_audio_dur = audio_metadata['total_duration']
        
        print(f"  ✓ TTS generation complete")
        print(f"    Generation time: {stage_times['tts']:.2f}s")
        print(f"    Audio files: {audio_metadata['beat_count']}")
        print(f"    Total audio duration: {total_audio_dur:.2f}s")
        print()

        # ===================================================================
        # STAGE 3: AUDIO TIMING MEASUREMENT
        # ===================================================================
        _step(3, TOTAL_STAGES, "Audio Timing Measurement")
        
        stage_start = time.perf_counter()
        
        # Update lesson spec with timing data
        lesson_spec['beats'] = enriched_beats
        lesson_spec['measured_duration'] = total_audio_dur
        
        # Save updated spec with timing
        _save_json(lesson_spec, spec_path)
        
        stage_times['timing'] = time.perf_counter() - stage_start
        
        print(f"  ✓ Audio timing measured")
        print(f"    Timing calculation: {stage_times['timing']:.4f}s")
        print(f"    Updated spec saved")
        print()

        # ===================================================================
        # STAGE 4: SCENE FILE GENERATION
        # ===================================================================
        _step(4, TOTAL_STAGES, "Scene File Generation")
        
        stage_start = time.perf_counter()
        
        # Create visual renderer service
        visual_service = create_visual_renderer(output_dir=run_dir)
        
        # Validate beats before generating scene
        validation_errors = visual_service.validate_beats(enriched_beats)
        if validation_errors:
            print("  [WARNING] Beat validation issues:")
            for err in validation_errors[:5]:  # Show first 5
                print(f"    - {err}")
            if len(validation_errors) > 5:
                print(f"    ... and {len(validation_errors) - 5} more")
            print()
        
        # Generate scene file
        try:
            scene_file = visual_service.generate_scene_file(
                beats=enriched_beats,
                output_filename="generated_scene.py"
            )
        except Exception as e:
            print(f"  [ERROR] Scene generation failed: {e}")
            raise
        
        stage_times['scene_gen'] = time.perf_counter() - stage_start
        
        print(f"  ✓ Scene file generated")
        print(f"    Generation time: {stage_times['scene_gen']:.4f}s")
        print(f"    Scene file: {os.path.basename(scene_file)}")
        print()

        # ===================================================================
        # STAGE 5: MANIM RENDERING (SILENT VIDEO)
        # ===================================================================
        _step(5, TOTAL_STAGES, "Manim Rendering (silent video)")
        
        stage_start = time.perf_counter()
        
        success, silent_video_path, manim_time = _render_manim(
            scene_file=scene_path,
            scene_class=SCENE_CLASS,
            quality_flag=QUALITY_FLAG,
            output_dir=run_dir
        )
        
        stage_times['manim'] = manim_time
        
        if not success:
            print("  [ERROR] Manim rendering failed")
            raise RuntimeError("Manim rendering failed")
        
        print(f"  ✓ Manim rendering complete")
        print(f"    Render time: {stage_times['manim']:.2f}s")
        print(f"    Silent video: {os.path.basename(silent_video_path)}")
        print()

        # ===================================================================
        # STAGE 6: AUDIO+VIDEO MUXING
        # ===================================================================
        _step(6, TOTAL_STAGES, "Audio+Video Muxing (FFmpeg)")
        
        stage_start = time.perf_counter()
        
        # Initialize muxing service
        muxing_service = create_muxing_service()
        
        # Collect audio files in order
        audio_files = [beat['audio_file'] for beat in enriched_beats]
        
        # Mux video with audio
        try:
            final_video = muxing_service.mux_video_with_beat_audio(
                video_path=silent_video_path,
                audio_files=audio_files,
                output_path=final_video_path,
                overwrite=True
            )
        except Exception as e:
            print(f"  [ERROR] Muxing failed: {e}")
            raise
        
        stage_times['muxing'] = time.perf_counter() - stage_start
        
        # Get final video info
        try:
            video_info = muxing_service.get_video_info(final_video)
            video_duration = video_info.get('duration')
        except:
            video_duration = None
        
        print(f"  ✓ Muxing complete")
        print(f"    Muxing time: {stage_times['muxing']:.2f}s")
        print(f"    Final video: {os.path.basename(final_video)}")
        print()

        # ===================================================================
        # STAGE 7: COMPLETE
        # ===================================================================
        _step(7, TOTAL_STAGES, "Complete")
        
        stage_times['complete'] = time.perf_counter() - stage_start
        
        print(f"  ✓ Pipeline complete")
        print()

        # Calculate total time
        total_time = time.perf_counter() - pipeline_start

        # Print final summary
        _print_final_summary(
            topic=topic,
            language=language,
            stage_times=stage_times,
            total_time=total_time,
            video_path=final_video,
            video_duration=video_duration,
            run_dir=run_dir,
            failed=False
        )

    except KeyboardInterrupt:
        print()
        print("  [INTERRUPTED] Pipeline cancelled by user")
        sys.exit(1)
    
    except Exception as e:
        total_time = time.perf_counter() - pipeline_start
        print()
        print(f"  [FATAL ERROR] {e}")
        _print_final_summary(
            topic=topic,
            language=language,
            stage_times=stage_times,
            total_time=total_time,
            video_path=None,
            video_duration=None,
            run_dir=run_dir,
            failed=True
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
