# Generated by LocalLearn AI
# Topic: Explain Binary Search
# Model: llama3:latest
#
# Render: python render.py generated_scene.py LocalLearnScene --low
# Re-generate: python generate.py "Explain Binary Search"

from manim import *


class LocalLearnScene(Scene):

    # Generated by LocalLearn AI
    # Topic: Binary Search

    def construct(self):

        # --- Scene 1: title ---
        _title = Text('Binary Search', font_size=52)
        self.play(Write(_title), run_time=1)
        self.wait(2.0)
        self.play(FadeOut(_title), run_time=0.5)

        # --- Scene 2: definition ---
        _hd = Text('Definition', font_size=36)
        _hd.to_edge(UP, buff=0.35)
        self.play(Write(_hd), run_time=0.8)
        _body = Text('Finding an element in a sorted array', font_size=28)
        _body.move_to(ORIGIN)
        self.play(FadeIn(_body, shift=UP*0.2), run_time=0.8)
        self.wait(3.5)
        self.play(FadeOut(VGroup(_hd, _body)), run_time=0.5)


        # --- Scene 3: explanation ---
        _hd = Text('Start at the middle, compare, and move towards the target', font_size=36)
        _hd.to_edge(UP, buff=0.35)
        self.play(Write(_hd), run_time=0.8)
        _pts = VGroup()
        _pts.add(Text('• Compare middle element', font_size=26))
        _pts.add(Text('• Move towards target', font_size=26))
        _pts.arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _pts.move_to(ORIGIN)
        self.play(FadeIn(_pts[0], shift=RIGHT*0.2), run_time=0.6)
        self.play(FadeIn(_pts[1], shift=RIGHT*0.2), run_time=0.6)
        self.wait(4.5)
        self.play(FadeOut(VGroup(_hd, _pts)), run_time=0.5)

        # --- Scene 4: array_search (binary search) ---
        _bs_vals = [1, 3, 5, 7, 9]
        _bs_tgt  = 5

        _hd = Text('Binary Search', font_size=36)
        _hd.to_edge(UP, buff=0.35)
        self.play(Write(_hd), run_time=0.8)

        # Build array
        _cells = VGroup()
        for _v in _bs_vals:
            _box   = Square(side_length=0.85, stroke_width=2.5)
            _lbl   = Text(str(_v), font_size=24)
            _lbl.move_to(_box.get_center())
            _cells.add(VGroup(_box, _lbl))
        _cells.arrange(RIGHT, buff=0.12)
        _cells.scale(0.95)
        _cells.move_to(ORIGIN + UP * 0.5)
        self.play(LaggedStart(
            *[FadeIn(c, shift=UP*0.15) for c in _cells],
            lag_ratio=0.1), run_time=1.2)

        _tgt_lbl = Text(f'Target: {_bs_tgt}', font_size=28)
        _tgt_lbl.to_edge(DOWN, buff=0.5)
        self.play(Write(_tgt_lbl), run_time=0.7)
        self.wait(1)

        # Step 1: lo=0 hi=4 mid=2
        _expl_0 = Text(
            f'lo=0  mid=2  hi=4',
            font_size=24
        )
        _expl_0.to_edge(DOWN, buff=1.1)
        self.play(FadeIn(_expl_0), run_time=0.5)

        _rect_0 = SurroundingRectangle(
            _cells[2], color=GREEN, buff=0.06, stroke_width=3
        )
        self.play(Create(_rect_0), run_time=0.6)
        _found_lbl = Text('FOUND!', font_size=32, color=GREEN)
        _found_lbl.next_to(_cells[2], UP, buff=0.4)
        self.play(Write(_found_lbl), run_time=0.6)
        self.play(Indicate(_cells[2], scale_factor=1.18, color=GREEN))
        self.wait(1.5)
        self.play(FadeOut(_found_lbl), FadeOut(_rect_0),
                  FadeOut(_expl_0), run_time=0.5)

        self.wait(1)
        self.play(
            FadeOut(_hd), FadeOut(_cells), FadeOut(_tgt_lbl),
            run_time=0.6)

        # --- Scene 5: formula ---
        _ftxt = Text('Time complexity', font_size=30)
        _ftxt.to_edge(UP, buff=1.0)
        self.play(Write(_ftxt), run_time=0.8)
        _fml = Text('O(log n)', font_size=56)
        _fml.move_to(ORIGIN)
        self.play(Write(_fml), run_time=1.0)
        self.wait(5.0)
        self.play(FadeOut(VGroup(_ftxt, _fml)), run_time=0.5)

        # --- Scene 6: comparison ---
        _cmp_groups = VGroup()
        _ci_lbl = Text('Linear Search', font_size=30)
        _ci_val = Text('O(n)', font_size=40)
        _ci_grp = VGroup(_ci_lbl, _ci_val)
        _ci_grp.arrange(DOWN, buff=0.3)
        _cmp_groups.add(_ci_grp)
        _ci_lbl = Text('Binary Search', font_size=30)
        _ci_val = Text('O(log n)', font_size=40)
        _ci_grp = VGroup(_ci_lbl, _ci_val)
        _ci_grp.arrange(DOWN, buff=0.3)
        _cmp_groups.add(_ci_grp)
        _cmp_groups.arrange(RIGHT, buff=2.0)
        _cmp_groups.move_to(ORIGIN)
        self.play(FadeIn(_cmp_groups, shift=UP*0.2), run_time=1.0)
        self.wait(5.5)
        self.play(FadeOut(_cmp_groups), run_time=0.5)

        # --- Scene 7: summary ---
        _sm_hd = Text('Efficient search in sorted arrays', font_size=36)
        _sm_hd.to_edge(UP, buff=0.35)
        self.play(Write(_sm_hd), run_time=0.8)
        _sm_pts = VGroup()
        _sm_pts.add(Text('• Start at middle', font_size=26))
        _sm_pts.add(Text('• Compare and move', font_size=26))
        _sm_pts.arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _sm_pts.move_to(ORIGIN)
        self.play(FadeIn(_sm_pts[0], shift=RIGHT*0.2), run_time=0.5)
        self.play(FadeIn(_sm_pts[1], shift=RIGHT*0.2), run_time=0.5)
        self.wait(4.9)
        self.play(FadeOut(VGroup(_sm_hd, _sm_pts)), run_time=0.5)

        # --- Outro ---
        _outro = Text('LocalLearn AI', font_size=48)
        _outro_sub = Text('Learn  ·  Visualize  ·  Understand', font_size=26)
        _outro_sub.next_to(_outro, DOWN, buff=0.3)
        self.play(Write(_outro), run_time=1.0)
        self.play(FadeIn(_outro_sub), run_time=0.8)
        self.wait(3)

