"""
LocalLearn AI - Full Pipeline (One Command)
--------------------------------------------
Usage:
    python generate.py "Explain Binary Search"
    python generate.py "Explain Binary Search" --language hi
    python generate.py "Explain Binary Search" --language ta

Supported language codes:
    en  English (default)
    hi  Hindi
    ta  Tamil
    te  Telugu
    mr  Marathi

Full pipeline runs automatically:
    [1/5] Connect to Ollama + generate compact lesson spec
    [2/5] Create lesson specification
    [3/5] Generate deterministic Manim animation code
    [4/5] Validate generated code
    [5/5] Render video with Manim

Output is organised under:
    output/<safe_topic>_<timestamp>/
        lesson_spec.json
        generated_scene.py
        video/  (Manim writes here automatically)
"""

import sys
import os
import re
import time
import json
import glob
import shutil
import subprocess
import datetime

from lesson_planner import generate_lesson_plan
from scene_builder  import build_manim_code
from validator      import validate_and_estimate
from language_codes import (
    LanguageCode,
    DEFAULT_LANGUAGE,
    LANGUAGE_NAMES,
    validate_language,
)

# ---------------------------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------------------------

MODEL         = "llama3:latest"
SCENE_CLASS   = "LocalLearnScene"
QUALITY_FLAG  = "-ql"   # low quality = fast rendering; change to -qm/-qh later
OUTPUT_ROOT   = "output"
RENDER_TIMEOUT = 300    # seconds — adjust upwards for high-quality renders

SEP = "  " + "-" * 43

# ---------------------------------------------------------------------------
# FILESYSTEM HELPERS
# ---------------------------------------------------------------------------

def _safe_name(topic: str) -> str:
    """Convert a topic string into a safe directory name."""
    name = topic.lower().strip()
    name = re.sub(r"[^\w\s-]", "", name)        # remove punctuation
    name = re.sub(r"[\s_-]+", "_", name)         # collapse spaces/dashes
    name = name.strip("_")
    return name[:60]                              # cap at 60 chars


def _make_run_dir(topic: str) -> str:
    """
    Create a unique output directory for this run.

    Format:  output/<safe_topic>_<YYYYMMDD_HHMMSS>/
    """
    ts      = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    dirname = f"{_safe_name(topic)}_{ts}"
    path    = os.path.join(OUTPUT_ROOT, dirname)
    os.makedirs(path, exist_ok=True)
    return path


def _save_json(spec: dict, path: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(spec, fh, indent=2)


def _save_code(path: str, topic: str, run_dir: str, code: str) -> None:
    scene_file = os.path.basename(path)
    header = (
        f"# Generated by LocalLearn AI\n"
        f"# Topic: {topic}\n"
        f"# Model: {MODEL}\n"
        f"#\n"
        f"# Output directory: {run_dir}\n"
        f"# Re-generate: python generate.py \"{topic}\"\n\n"
    )
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(header + code + "\n")

# ---------------------------------------------------------------------------
# MP4 DETECTION
# ---------------------------------------------------------------------------

def _find_mp4(scene_file: str, scene_class: str) -> str | None:
    """
    Search for the MP4 Manim produced.

    Manim writes output to:
        media/videos/<scene_stem>/<quality>/  (relative to CWD or scene file dir)

    Returns the path to the MP4 if found, else None.
    """
    scene_stem = os.path.splitext(os.path.basename(scene_file))[0]

    # Patterns Manim uses for output paths
    search_patterns = [
        # Alongside the scene file
        os.path.join(os.path.dirname(scene_file), "media", "videos",
                     scene_stem, "**", "*.mp4"),
        # Relative to CWD
        os.path.join("media", "videos", scene_stem, "**", "*.mp4"),
        # Absolute anywhere under media/
        os.path.join("media", "**", f"{scene_class}*.mp4"),
    ]

    for pattern in search_patterns:
        matches = glob.glob(pattern, recursive=True)
        if matches:
            # Return the most recently modified MP4
            matches.sort(key=os.path.getmtime, reverse=True)
            return matches[0]

    return None


def _estimate_video_duration(mp4_path: str) -> float | None:
    """
    Estimate video duration via ffprobe if available.
    Returns seconds as float, or None if ffprobe is not available.
    """
    try:
        result = subprocess.run(
            [
                "ffprobe", "-v", "quiet",
                "-print_format", "json",
                "-show_format",
                mp4_path,
            ],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            data = json.loads(result.stdout)
            duration = data.get("format", {}).get("duration")
            if duration:
                return float(duration)
    except Exception:
        pass
    return None

# ---------------------------------------------------------------------------
# MANIM RENDERER
# ---------------------------------------------------------------------------

def _render(scene_file: str, scene_class: str, quality_flag: str) -> tuple:
    """
    Invoke Manim via subprocess.

    Uses sys.executable so the same virtual environment is used.

    Returns:
        (returncode, combined_output, elapsed_seconds)
    """
    cmd = [
        sys.executable, "-m", "manim",
        quality_flag,
        scene_file,
        scene_class,
    ]

    start        = time.perf_counter()
    output_lines = []

    try:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,   # merge stderr into stdout
            text=True,
            bufsize=1,
        )

        for line in process.stdout:
            print(line, end="", flush=True)
            output_lines.append(line)

        process.wait()
        returncode = process.returncode

    except FileNotFoundError:
        elapsed = time.perf_counter() - start
        return -1, "Manim executable not found.", elapsed
    except KeyboardInterrupt:
        print()
        print("  [INTERRUPTED] Rendering cancelled.")
        sys.exit(1)

    elapsed  = time.perf_counter() - start
    combined = "".join(output_lines)
    return returncode, combined, elapsed

# ---------------------------------------------------------------------------
# SYNTAX REPAIR (one attempt via Ollama — only if validation fails)
# ---------------------------------------------------------------------------

def _attempt_repair(code: str, syntax_err) -> tuple:
    """One Ollama repair attempt. Returns (repaired_code|None, elapsed)."""
    import urllib.request

    err_msg  = syntax_err.msg    if hasattr(syntax_err, "msg")    else str(syntax_err)
    err_line = syntax_err.lineno if hasattr(syntax_err, "lineno") else "?"

    print(f"  Attempting syntax repair (line {err_line}: {err_msg})...")

    prompt = (
        "Fix the Python syntax error in this Manim code.\n"
        "Do NOT redesign the animation. Fix ONLY the syntax error.\n"
        "Return the complete corrected Python code. No Markdown.\n"
        f"\nSyntax error: {err_msg}\nLine: {err_line}\n\nCode:\n{code}\n"
    )
    payload = {
        "model": MODEL, "prompt": prompt, "stream": False,
        "options": {"num_predict": 1500, "temperature": 0.1},
    }
    body = json.dumps(payload).encode("utf-8")
    req  = urllib.request.Request(
        "http://localhost:11434/api/generate", data=body,
        headers={"Content-Type": "application/json"}, method="POST",
    )
    start = time.perf_counter()
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        raw = data.get("response", "")
    except Exception as exc:
        print(f"  Repair failed: {exc}")
        return None, time.perf_counter() - start
    elapsed = time.perf_counter() - start

    # Strip fences / preamble
    text = raw.strip()
    if "```" in text:
        lns, inside, out = text.splitlines(), False, []
        for ln in lns:
            if not inside:
                if ln.strip().startswith("```"):
                    inside = True
            else:
                if ln.strip() == "```":
                    break
                out.append(ln)
        if out:
            text = "\n".join(out).strip()
    lns = text.splitlines()
    for i, ln in enumerate(lns):
        s = ln.strip()
        if s.startswith("from manim import") or s.startswith("import manim"):
            text = "\n".join(lns[i:]).strip()
            break

    return (text if text else None), elapsed

# ---------------------------------------------------------------------------
# DISPLAY
# ---------------------------------------------------------------------------

def _banner(topic: str, language: LanguageCode) -> None:
    lang_display = LANGUAGE_NAMES[language]
    print()
    print(SEP)
    print("  LocalLearn AI")
    print(SEP)
    print(f"  Topic:    {topic}")
    print(f"  Language: {lang_display} ({language.value})")
    print(f"  Model:    {MODEL}")
    print(SEP)
    print()


def _step(n: int, total: int, label: str) -> None:
    print(f"  [{n}/{total}] {label}")


def _print_final_summary(
    topic: str,
    language: LanguageCode,
    conn_time: float,
    planning_time: float,
    build_time: float,
    val_time: float,
    render_time: float,
    repair_time: float,
    total_time: float,
    video_path: str | None,
    video_duration: float | None,
    estimated_duration: float,
    run_dir: str,
    failed: bool = False,
) -> None:
    lang_display = LANGUAGE_NAMES[language]
    print()
    print(SEP)
    if failed:
        print("  LOCALLEARN AI — FAILED")
    else:
        print("  LOCALLEARN AI COMPLETE")
    print(SEP)
    print()
    print(f"  Topic:              {topic}")
    print(f"  Language:           {lang_display} ({language.value})")
    print()
    print(f"  Ollama connection:  {conn_time:.2f} sec")
    print(f"  Lesson planning:    {planning_time:.2f} sec")
    print(f"  Code generation:    {build_time:.4f} sec  (deterministic)")
    if repair_time > 0:
        print(f"  Repair:             {repair_time:.2f} sec")
    print(f"  Validation:         {val_time:.2f} sec")
    if not failed:
        print(f"  Render time:        {render_time:.2f} sec")
    print()
    print(f"  Total time:         {total_time:.2f} sec")
    print()

    if not failed:
        if video_path:
            print(f"  Video:")
            print(f"    {os.path.abspath(video_path)}")
            print()
        if video_duration is not None:
            print(f"  Video duration:     {video_duration:.1f} sec")
        else:
            print(f"  Est. duration:      {estimated_duration:.1f} sec")
        print()
        print(f"  Output directory:")
        print(f"    {os.path.abspath(run_dir)}")
    else:
        print("  Pipeline did not complete successfully.")
        print(f"  Partial output in: {os.path.abspath(run_dir)}")

    print()
    print(SEP)
    print()

# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main() -> None:

    pipeline_start = time.perf_counter()

    # ------------------------------------------------------------------
    # Arguments
    # ------------------------------------------------------------------
    # Usage:
    #   python generate.py "topic"
    #   python generate.py "topic" --language hi
    # ------------------------------------------------------------------
    args = sys.argv[1:]

    if not args or not args[0].strip():
        print()
        print("  Usage:   python generate.py \"<topic>\" [--language <code>]")
        print("  Example: python generate.py \"Explain Binary Search\" --language hi")
        print()
        print("  Supported language codes:")
        for lc in LanguageCode:
            default_marker = "  (default)" if lc == DEFAULT_LANGUAGE else ""
            print(f"    {lc.value}  {LANGUAGE_NAMES[lc]}{default_marker}")
        print()
        sys.exit(1)

    topic = args[0].strip()

    # Parse optional --language flag
    language = DEFAULT_LANGUAGE
    if "--language" in args:
        lang_idx = args.index("--language")
        if lang_idx + 1 >= len(args):
            print("\n  [ERROR] --language requires a value, e.g. --language hi\n")
            sys.exit(1)
        lang_code = args[lang_idx + 1]
        try:
            language = validate_language(lang_code)
        except ValueError as exc:
            print(f"\n  [ERROR] {exc}\n")
            sys.exit(1)

    _banner(topic, language)

    # Create the unique output directory for this run
    run_dir = _make_run_dir(topic)

    spec_path  = os.path.join(run_dir, "lesson_spec.json")
    scene_path = os.path.join(run_dir, "generated_scene.py")

    # Timing accumulators
    conn_time    = 0.0
    planning_time = 0.0
    build_time   = 0.0
    val_time     = 0.0
    render_time  = 0.0
    repair_time  = 0.0
    estimated_dur = 0.0

    # ------------------------------------------------------------------
    # [1/5] Connect to Ollama + generate lesson spec
    # ------------------------------------------------------------------
    TOTAL_STEPS = 5
    _step(1, TOTAL_STEPS, "Connecting to Ollama...")

    conn_start = time.perf_counter()
    try:
        lesson_spec, planning_time = generate_lesson_plan(topic, language=language)
    except RuntimeError as exc:
        print(f"\n  [ERROR] {exc}")
        sys.exit(1)
    except TimeoutError as exc:
        print(f"\n  [TIMEOUT] {exc}")
        sys.exit(1)
    except ValueError as exc:
        print(f"\n  [ERROR] {exc}")
        sys.exit(1)

    conn_time = time.perf_counter() - conn_start

    print("  Ollama connection successful.")
    print(f"  Connection time: {conn_time:.2f} sec")
    print()

    # ------------------------------------------------------------------
    # [2/5] Lesson specification
    # ------------------------------------------------------------------
    _step(2, TOTAL_STEPS, "Creating lesson specification...")

    _save_json(lesson_spec, spec_path)

    n_scenes     = len(lesson_spec.get("scenes", []))
    target_dur   = lesson_spec.get("target_duration", 75)

    print(f"  Lesson specification generated.")
    print(f"  Planning time: {planning_time:.2f} sec")
    print(f"  Scenes: {n_scenes}")
    print(f"  Target duration: {target_dur} sec")
    print(f"  Saved: {spec_path}")
    print()

    # ------------------------------------------------------------------
    # [3/5] Generate Manim animation code (deterministic — no LLM)
    # ------------------------------------------------------------------
    _step(3, TOTAL_STEPS, "Generating Manim animation...")

    build_start = time.perf_counter()
    code        = build_manim_code(lesson_spec)
    build_time  = time.perf_counter() - build_start

    print(f"  Animation code generated.")
    print(f"  Code generation time: {build_time:.4f} sec")
    print()

    # ------------------------------------------------------------------
    # [4/5] Validate
    # ------------------------------------------------------------------
    _step(4, TOTAL_STEPS, "Validating animation...")

    val_start = time.perf_counter()
    result    = validate_and_estimate(code)
    val_time  = time.perf_counter() - val_start

    estimated_dur = result.get("estimated_duration", 0.0)

    # Report validation
    syntax_ok  = result["syntax_valid"]
    struct_ok  = not result["structure_errors"]
    api_warns  = result.get("api_warnings", [])

    if syntax_ok and struct_ok and not api_warns:
        print(f"  Validation: PASS")
    else:
        if not syntax_ok:
            err = result["syntax_error"]
            ln  = err.lineno if hasattr(err, "lineno") else "?"
            print(f"  Syntax:    FAIL  (line {ln})")
        else:
            print(f"  Syntax:    PASS")
        print(f"  Structure: {'PASS' if struct_ok else 'FAIL'}")
        if api_warns:
            print(f"  API scan:  WARN  ({len(api_warns)} issue(s))")
    print(f"  Validation time: {val_time:.2f} sec")
    print()

    # Handle syntax failure — one repair attempt
    if not syntax_ok:
        repaired, repair_time = _attempt_repair(code, result["syntax_error"])
        if repaired:
            result = validate_and_estimate(repaired)
            if result["syntax_valid"]:
                print("  Syntax:    PASS  (after repair)")
                code = repaired
                estimated_dur = result.get("estimated_duration", 0.0)
            else:
                print("  Syntax:    FAIL  (repair did not fix it)")
        else:
            print("  Repair failed.")

        if not result["syntax_valid"]:
            # Save invalid code for inspection
            inv_path = os.path.join(run_dir, "generated_scene_invalid.py")
            _save_code(inv_path, topic, run_dir, code)
            print(f"  Invalid code saved: {inv_path}")
            total = time.perf_counter() - pipeline_start
            _print_final_summary(
                topic, language, conn_time, planning_time, build_time, val_time,
                render_time, repair_time, total,
                video_path=None, video_duration=None,
                estimated_duration=estimated_dur, run_dir=run_dir, failed=True
            )
            sys.exit(1)

    # Handle API warnings — pre-render repair
    if api_warns:
        print("  API warnings — attempting pre-render repair...")
        first_warn  = api_warns[0]
        first_match = first_warn["lines"][0] if first_warn["lines"] else (0, "")
        lineno, src = first_match
        all_labels  = "; ".join(w["label"] for w in api_warns)
        error_info  = {
            "error_type":  "APIWarning",
            "error_msg":   all_labels,
            "error_line":  lineno,
            "source_line": src,
        }
        try:
            from manim_repair import repair_manim_code
            repaired, api_rt = repair_manim_code(code, error_info, attempt_number=1)
            repair_time += api_rt
            if repaired:
                new_result = validate_and_estimate(repaired)
                remaining  = new_result.get("api_warnings", [])
                if not remaining:
                    print("  API scan:  PASS  (after repair)")
                else:
                    print(f"  API scan:  WARN  ({len(remaining)} issue(s) remain — proceeding)")
                code          = repaired
                result        = new_result
                estimated_dur = result.get("estimated_duration", 0.0)
            else:
                print("  Pre-render repair failed — proceeding anyway")
        except ImportError:
            print("  manim_repair not available — proceeding without API repair")
        print()

    # Save the validated scene file inside run_dir
    _save_code(scene_path, topic, run_dir, code)
    print(f"  Scene file saved: {scene_path}")
    print()

    # ------------------------------------------------------------------
    # [5/5] Render
    # ------------------------------------------------------------------
    _step(5, TOTAL_STEPS, "Rendering video...")
    print()

    render_start = time.perf_counter()
    returncode, combined_output, render_time = _render(
        scene_path, SCENE_CLASS, QUALITY_FLAG
    )
    # render_time already set by _render, but recalculate for consistency
    render_time = time.perf_counter() - render_start

    print()   # blank line after Manim's own output

    if returncode != 0:
        # Extract error from Manim output
        print(SEP)
        print("  Rendering FAILED")
        print(SEP)
        # Print last 20 lines of Manim output as the error context
        manim_lines = [l for l in combined_output.splitlines() if l.strip()]
        for line in manim_lines[-20:]:
            print(f"  {line}")
        print()
        total = time.perf_counter() - pipeline_start
        _print_final_summary(
            topic, language, conn_time, planning_time, build_time, val_time,
            render_time, repair_time, total,
            video_path=None, video_duration=None,
            estimated_duration=estimated_dur, run_dir=run_dir, failed=True
        )
        sys.exit(1)

    # Rendering succeeded — find the MP4
    render_time_actual = time.perf_counter() - render_start
    mp4_path       = _find_mp4(scene_path, SCENE_CLASS)
    video_duration = _estimate_video_duration(mp4_path) if mp4_path else None

    # Copy MP4 into run_dir as video.mp4 for easy access
    if mp4_path:
        dest_mp4 = os.path.join(run_dir, "video.mp4")
        try:
            shutil.copy2(mp4_path, dest_mp4)
            # Prefer the copy in run_dir so the path is clean
            mp4_path = dest_mp4
        except Exception:
            pass  # original path still valid

    print(f"  Rendering completed.")
    print(f"  Render time: {render_time:.2f} sec")
    print()

    # ------------------------------------------------------------------
    # Final summary
    # ------------------------------------------------------------------
    total_time = time.perf_counter() - pipeline_start

    _print_final_summary(
        topic, language, conn_time, planning_time, build_time, val_time,
        render_time, repair_time, total_time,
        video_path=mp4_path,
        video_duration=video_duration,
        estimated_duration=estimated_dur,
        run_dir=run_dir,
        failed=False,
    )


if __name__ == "__main__":
    main()
