"""
Deterministic visual renderer for LocalLearn AI.

This module generates ManimGL scene files from lesson specifications.
It does NOT import ManimGL directly - scene files are standalone Python
scripts that are executed by the manimgl.exe process.
"""

import json
from pathlib import Path


class VisualRenderService:
    """
    Service that generates ManimGL scene files from lesson beats.
    
    The generated scene files are standalone Python scripts that:
    1. Import from manimlib (ManimGL)
    2. Import visual renderers from the visuals/ package
    3. Define a LessonScene class with embedded beat data
    4. Can be rendered by calling: manimgl generated_scene.py GeneratedLessonScene
    """
    
    def __init__(self, output_dir: str = "."):
        """
        Initialize the visual render service.
        
        Parameters
        ----------
        output_dir : str
            Directory where scene files will be written.
        """
        self.output_dir = output_dir
    
    def generate_scene_file(
        self,
        beats: list[dict],
        output_filename: str = "generated_scene.py"
    ) -> str:
        """
        Generate a standalone ManimGL scene file.
        
        Parameters
        ----------
        beats : list[dict]
            Enriched beats with visual plans and audio timing.
        output_filename : str
            Name of the output Python file.
        
        Returns
        -------
        str
            Path to the generated scene file.
        """
        output_path = Path(self.output_dir) / output_filename
        
        # Get absolute path to the LocalLearn project root
        # This is where the visuals module is located
        project_root = str(Path(__file__).parent.absolute())
        
        # Serialize beats to embed in the file
        beats_json = json.dumps(beats, indent=2)
        
        # Generate the complete scene file
        # This file will be executed in the ManimGL environment
        # Ensure we use forward slashes for Python import paths
        project_root_normalized = project_root.replace('\\', '\\\\')
        
        scene_code = f'''"""
Auto-generated ManimGL scene for LocalLearn AI.

This file was generated by visual_renderer.py and contains a complete
ManimGL scene with beats and visual plans embedded.

To render:
    manimgl {output_filename} GeneratedLessonScene
"""

from manimlib import *
import json
import sys

# Add LocalLearn project root to path to import local modules
# This path is set at scene generation time to the absolute path of the project
PROJECT_ROOT = r"{project_root_normalized}"
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

# Import visual components (these require ManimGL to be available)
from visuals.base import VisualRenderer, VisualAction
from visuals.insertion_sort import InsertionSortRenderer
from visuals.binary_search import BinarySearchRenderer
from visuals.linear_search import LinearSearchRenderer
from visuals.bubble_sort import BubbleSortRenderer
from visuals.selection_sort import SelectionSortRenderer

# Embedded lesson beats with timing and visual plans
BEATS = {beats_json}


class LessonScene(Scene):
    """
    Main ManimGL scene that orchestrates beat-by-beat animation.
    
    This scene is constructed dynamically from lesson beats with visual plans
    and audio timing information.
    """
    
    def __init__(self, beats: list[dict], **kwargs):
        super().__init__(**kwargs)
        self.beats = beats
        self.renderer_cache: dict[str, VisualRenderer] = {{}}
    
    def construct(self):
        """Main ManimGL construct method that builds the animation."""
        total_audio_duration = sum(beat.get("audio_duration", 3.0) for beat in self.beats)
        
        print(f"[LessonScene] Starting scene construction")
        print(f"[LessonScene] Total beats: {{len(self.beats)}}")
        print(f"[LessonScene] Total audio duration: {{total_audio_duration:.2f}}s")
        
        for i, beat in enumerate(self.beats):
            beat_duration = beat.get("audio_duration", 3.0)
            print(f"[LessonScene] Rendering beat {{i+1}}/{{len(self.beats)}}: {{beat.get('id', '?')}} (duration: {{beat_duration:.2f}}s)")
            self._render_beat(beat)
        
        # Add buffer at the end to ensure video doesn't cut off early
        buffer_duration = 1.0
        print(f"[LessonScene] Adding {{buffer_duration}}s buffer at end")
        self.wait(buffer_duration)
        
        actual_duration = total_audio_duration + buffer_duration
        print(f"[LessonScene] Scene construction complete")
        print(f"[LessonScene] Expected video duration: {{actual_duration:.2f}}s")
    
    def _render_beat(self, beat: dict) -> None:
        """Render a single beat with its visual plan."""
        visual = beat.get("visual")
        duration = beat.get("audio_duration", 3.0)
        language = beat.get("language", "en")
        
        if not visual:
            self.wait(duration)
            return
        
        visual_type = visual.get("type")
        action = visual.get("action")
        data = visual.get("data", {{}})
        emphasis = visual.get("emphasis", [])
        
        if visual_type == "array":
            self._render_array_visual(action, data, emphasis, duration, language)
        elif visual_type == "text":
            self._render_text_visual(action, data, duration, language)
        elif visual_type == "diagram":
            self._render_diagram_visual(action, data, duration, language)
        else:
            print(f"[LessonScene] Warning: unknown visual type '{{visual_type}}'")
            self.wait(duration)
    
    def _render_array_visual(self, action: str, data: dict, emphasis: list[int], duration: float, language: str) -> None:
        """Render array-based visualizations."""
        insertion_actions = {{"show_array", "select_key", "compare", "shift", "insert", "mark_sorted", "show_complexity"}}
        binary_search_actions = {{"show_array", "check_middle", "found", "eliminate_half", "show_complexity"}}
        linear_search_actions = {{"show_array", "set_pointer", "move_pointer", "compare_element", "found", "not_found", "show_result", "show_complexity"}}
        bubble_sort_actions = {{"show_array", "compare_adjacent", "swap", "mark_sorted", "show_complexity"}}
        selection_sort_actions = {{"show_array", "find_min", "swap_with_min", "mark_sorted", "show_complexity"}}
        
        renderer_type = None
        if action in insertion_actions:
            renderer_type = "insertion_sort"
        elif action in binary_search_actions:
            renderer_type = "binary_search"
        elif action in linear_search_actions:
            renderer_type = "linear_search"
        elif action in bubble_sort_actions:
            renderer_type = "bubble_sort"
        elif action in selection_sort_actions:
            renderer_type = "selection_sort"
        else:
            print(f"[LessonScene] Warning: unknown array action '{{action}}'")
            self.wait(duration)
            return
        
        renderer = self._get_renderer(renderer_type, language)
        
        try:
            renderer.render_action(
                VisualAction(
                    type="array",
                    action=action,
                    data=data,
                    emphasis=emphasis,
                    duration=duration,
                ),
                beat_duration=duration,
            )
        except Exception as e:
            print(f"[LessonScene] Error executing action '{{action}}': {{e}}")
            self.wait(duration)
    
    def _render_text_visual(self, action: str, data: dict, duration: float, language: str) -> None:
        """Render text-based visualizations."""
        text_content = data.get("text", "")
        if not text_content:
            self.wait(duration)
            return
        
        text_obj = Text(text_content, font_size=36)
        
        if action == "show":
            self.play(text_obj.animate.scale(1.0), run_time=min(1.0, duration * 0.3))
            self.wait(max(0, duration - 1.0))
            self.play(text_obj.animate.scale(0), run_time=min(1.0, duration * 0.2))
        elif action == "fade_in":
            self.play(text_obj.animate.set_opacity(1), run_time=duration)
        elif action == "fade_out":
            self.play(text_obj.animate.set_opacity(0), run_time=duration)
        else:
            self.add(text_obj)
            self.wait(duration)
            self.remove(text_obj)
    
    def _render_diagram_visual(self, action: str, data: dict, duration: float, language: str) -> None:
        """Render diagram-based visualizations (not yet implemented)."""
        print(f"[LessonScene] Warning: diagram visuals not yet implemented")
        self.wait(duration)
    
    def _get_renderer(self, renderer_type: str, language: str) -> VisualRenderer:
        """Get or create a renderer instance."""
        cache_key = f"{{renderer_type}}_{{language}}"
        
        if cache_key not in self.renderer_cache:
            if renderer_type == "insertion_sort":
                self.renderer_cache[cache_key] = InsertionSortRenderer(self, language=language)
            elif renderer_type == "binary_search":
                self.renderer_cache[cache_key] = BinarySearchRenderer(self, language=language)
            elif renderer_type == "linear_search":
                self.renderer_cache[cache_key] = LinearSearchRenderer(self, language=language)
            elif renderer_type == "bubble_sort":
                self.renderer_cache[cache_key] = BubbleSortRenderer(self, language=language)
            elif renderer_type == "selection_sort":
                self.renderer_cache[cache_key] = SelectionSortRenderer(self, language=language)
            else:
                raise ValueError(f"Unknown renderer type: {{renderer_type}}")
        
        return self.renderer_cache[cache_key]


class GeneratedLessonScene(LessonScene):
    """The main scene to render."""
    
    def __init__(self, **kwargs):
        super().__init__(beats=BEATS, **kwargs)
'''
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(scene_code)
        
        print(f"[VisualRenderService] Generated scene file: {output_path}")
        
        return str(output_path)
    
    def validate_beats(self, beats: list[dict]) -> list[str]:
        """
        Validate that beats have required fields for rendering.
        
        Parameters
        ----------
        beats : list[dict]
            Beats to validate.
        
        Returns
        -------
        list[str]
            List of validation errors (empty if valid).
        """
        errors = []
        
        for i, beat in enumerate(beats):
            if not isinstance(beat, dict):
                errors.append(f"Beat {i} is not a dict")
                continue
            
            # Check required fields
            if "audio_duration" not in beat:
                errors.append(f"Beat {i} ({beat.get('id', '?')}) missing 'audio_duration'")
            
            # Visual plan validation
            visual = beat.get("visual")
            if visual:
                if not isinstance(visual, dict):
                    errors.append(f"Beat {i} ({beat.get('id', '?')}) visual is not a dict")
                    continue
                
                if "type" not in visual:
                    errors.append(f"Beat {i} ({beat.get('id', '?')}) visual missing 'type'")
                if "action" not in visual:
                    errors.append(f"Beat {i} ({beat.get('id', '?')}) visual missing 'action'")
                if "data" not in visual:
                    errors.append(f"Beat {i} ({beat.get('id', '?')}) visual missing 'data'")
        
        return errors


def create_visual_renderer(output_dir: str = ".") -> VisualRenderService:
    """
    Factory function to create a VisualRenderService.
    
    Parameters
    ----------
    output_dir : str, optional
        Directory for output files.
    
    Returns
    -------
    VisualRenderService
        Ready-to-use visual render service.
    """
    return VisualRenderService(output_dir=output_dir)
