"""
Auto-generated Manim scene for LocalLearn AI.

This file was generated by visual_renderer.py and contains a complete
Manim scene with beats and visual plans embedded.

To render:
    manim -pql test_scene.py LessonScene
"""

from manim import Scene
import json

# Import visual renderers
import sys
from pathlib import Path

# Add parent directory to path to import local modules
sys.path.insert(0, str(Path(__file__).parent))

from visual_renderer import LessonScene

# Embedded lesson beats with timing and visual plans
BEATS = [
  {
    "id": "beat_1",
    "concept": "introduction",
    "narration": "Insertion sort is a simple sorting algorithm.",
    "visual_text": "Insertion Sort",
    "importance": "key",
    "language": "en",
    "audio_file": "beat_1.wav",
    "audio_duration": 3.5,
    "start_time": 0.0,
    "end_time": 3.5,
    "visual": {
      "type": "array",
      "action": "show_array",
      "data": {
        "values": [
          5,
          2,
          8,
          3,
          1
        ]
      }
    }
  },
  {
    "id": "beat_2",
    "concept": "step_1",
    "narration": "We select the second element as the key.",
    "visual_text": "Select Key",
    "importance": "normal",
    "language": "en",
    "audio_file": "beat_2.wav",
    "audio_duration": 4.2,
    "start_time": 3.5,
    "end_time": 7.7,
    "visual": {
      "type": "array",
      "action": "select_key",
      "data": {
        "index": 1
      }
    }
  }
]


class GeneratedLessonScene(LessonScene):
    """The main scene to render."""
    
    def __init__(self, **kwargs):
        super().__init__(beats=BEATS, **kwargs)


# For convenience, expose as LessonScene too
LessonScene = GeneratedLessonScene
