# Generated by LocalLearn AI
# Topic: explain bubble sort
# Model: llama3:latest
#
# Output directory: output\explain_bubble_sort_20261005_230234
# Re-generate: python generate.py "explain bubble sort"

from manim import *


class LocalLearnScene(Scene):

    # Generated by LocalLearn AI
    # Topic: Bubble Sort

    def construct(self):

        # --- Scene 1: title ---
        _title = Text('Bubble Sort', font_size=52)
        self.play(Write(_title), run_time=1)
        self.wait(2.0)
        self.play(FadeOut(_title), run_time=0.5)

        # --- Scene 2: definition ---
        _hd = Text('Definition', font_size=36)
        _hd.to_edge(UP, buff=0.35)
        self.play(Write(_hd), run_time=0.8)
        _body = Text('Sorting algorithm', font_size=28)
        _body.move_to(ORIGIN)
        self.play(FadeIn(_body, shift=UP*0.2), run_time=0.8)
        self.wait(3.5)
        self.play(FadeOut(VGroup(_hd, _body)), run_time=0.5)


        # --- Scene 3: explanation ---
        _hd = Text('Comparing adjacent elements', font_size=36)
        _hd.to_edge(UP, buff=0.35)
        self.play(Write(_hd), run_time=0.8)
        _pts = VGroup()
        _pts.add(Text('• swapping if out of order', font_size=26))
        _pts.arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _pts.move_to(ORIGIN)
        self.play(FadeIn(_pts[0], shift=RIGHT*0.2), run_time=0.6)
        self.wait(5.5)
        self.play(FadeOut(VGroup(_hd, _pts)), run_time=0.5)

        # --- Scene 4: array_search (binary search) ---
        _bs_vals = [1, 3, 2, 4]
        _bs_tgt  = 0

        _hd = Text('Binary Search', font_size=36)
        _hd.to_edge(UP, buff=0.35)
        self.play(Write(_hd), run_time=0.8)

        # Build array
        _cells = VGroup()
        for _v in _bs_vals:
            _box   = Square(side_length=0.85, stroke_width=2.5)
            _lbl   = Text(str(_v), font_size=24)
            _lbl.move_to(_box.get_center())
            _cells.add(VGroup(_box, _lbl))
        _cells.arrange(RIGHT, buff=0.12)
        _cells.scale(0.95)
        _cells.move_to(ORIGIN + UP * 0.5)
        self.play(LaggedStart(
            *[FadeIn(c, shift=UP*0.15) for c in _cells],
            lag_ratio=0.1), run_time=1.2)

        _tgt_lbl = Text(f'Target: {_bs_tgt}', font_size=28)
        _tgt_lbl.to_edge(DOWN, buff=0.5)
        self.play(Write(_tgt_lbl), run_time=0.7)
        self.wait(1)

        # Step 1: lo=0 hi=3 mid=1
        _expl_0 = Text(
            f'lo=0  mid=1  hi=3',
            font_size=24
        )
        _expl_0.to_edge(DOWN, buff=1.1)
        self.play(FadeIn(_expl_0), run_time=0.5)

        _rect_0 = SurroundingRectangle(
            _cells[1], color=YELLOW, buff=0.06, stroke_width=3
        )
        self.play(Create(_rect_0), run_time=0.6)
        _dir_lbl = Text(
            f'{_bs_vals[1]} vs {_bs_tgt} — discard left half',
            font_size=22
        )
        _dir_lbl.to_edge(DOWN, buff=0.15)
        self.play(Write(_dir_lbl), run_time=0.5)
        self.wait(0.8)
        self.play(
            *[_cells[i].animate.set_opacity(0.18)
              for i in [1, 2, 3]],
            run_time=0.7)
        self.wait(0.5)
        self.play(
            FadeOut(_rect_0),
            FadeOut(_expl_0),
            FadeOut(_dir_lbl),
            run_time=0.4)

        # Step 2: lo=0 hi=0 mid=0
        _expl_1 = Text(
            f'lo=0  mid=0  hi=0',
            font_size=24
        )
        _expl_1.to_edge(DOWN, buff=1.1)
        self.play(FadeIn(_expl_1), run_time=0.5)

        _rect_1 = SurroundingRectangle(
            _cells[0], color=YELLOW, buff=0.06, stroke_width=3
        )
        self.play(Create(_rect_1), run_time=0.6)
        _dir_lbl = Text(
            f'{_bs_vals[0]} vs {_bs_tgt} — discard left half',
            font_size=22
        )
        _dir_lbl.to_edge(DOWN, buff=0.15)
        self.play(Write(_dir_lbl), run_time=0.5)
        self.wait(0.8)
        self.play(
            *[_cells[i].animate.set_opacity(0.18)
              for i in [0, 1, 2, 3]],
            run_time=0.7)
        self.wait(0.5)
        self.play(
            FadeOut(_rect_1),
            FadeOut(_expl_1),
            FadeOut(_dir_lbl),
            run_time=0.4)

        self.wait(1)
        self.play(
            FadeOut(_hd), FadeOut(_cells), FadeOut(_tgt_lbl),
            run_time=0.6)

        # --- Scene 5: array_sort (bubble sort) ---
        _sort_vals = [1, 3, 2, 4]
        _svals = list(_sort_vals)

        _hd = Text('Bubble Sort', font_size=36)
        _hd.to_edge(UP, buff=0.35)
        self.play(Write(_hd), run_time=0.8)

        def _make_cells(vals):
            cells = VGroup()
            for v in vals:
                box = Square(side_length=0.85, stroke_width=2.5)
                lbl = Text(str(v), font_size=26)
                lbl.move_to(box.get_center())
                cells.add(VGroup(box, lbl))
            cells.arrange(RIGHT, buff=0.12)
            cells.move_to(ORIGIN)
            return cells

        _cells = _make_cells(_svals)
        self.play(LaggedStart(
            *[FadeIn(c, shift=UP*0.15) for c in _cells],
            lag_ratio=0.1), run_time=1.0)
        self.wait(0.5)

        # Bubble sort passes (up to 3 passes shown)
        _passes = 0
        for _pass in range(len(_svals) - 1):
            if _passes >= 3:
                break
            _swapped = False
            for _j in range(len(_svals) - 1 - _pass):
                if _svals[_j] > _svals[_j + 1]:
                    _svals[_j], _svals[_j + 1] = _svals[_j + 1], _svals[_j]
                    _swapped = True
                    _new = _make_cells(_svals)
                    self.play(ReplacementTransform(_cells, _new), run_time=0.5)
                    _cells = _new
            if not _swapped:
                break
            _passes += 1

        _done = Text('Sorted!', font_size=32, color=GREEN)
        _done.to_edge(DOWN, buff=0.5)
        self.play(Write(_done), run_time=0.6)
        self.wait(1.5)
        self.play(FadeOut(VGroup(_hd, _cells, _done)), run_time=0.6)

        # --- Scene 6: formula ---
        _ftxt = Text('Time complexity', font_size=30)
        _ftxt.to_edge(UP, buff=1.0)
        self.play(Write(_ftxt), run_time=0.8)
        _fml = Text('O(n^2)', font_size=56)
        _fml.move_to(ORIGIN)
        self.play(Write(_fml), run_time=1.0)
        self.wait(5.0)
        self.play(FadeOut(VGroup(_ftxt, _fml)), run_time=0.5)

        # --- Scene 7: summary ---
        _sm_hd = Text('Bubble Sort', font_size=36)
        _sm_hd.to_edge(UP, buff=0.35)
        self.play(Write(_sm_hd), run_time=0.8)
        _sm_pts = VGroup()
        _sm_pts.add(Text('• simple to implement', font_size=26))
        _sm_pts.add(Text('• inefficient for large datasets', font_size=26))
        _sm_pts.arrange(DOWN, aligned_edge=LEFT, buff=0.3)
        _sm_pts.move_to(ORIGIN)
        self.play(FadeIn(_sm_pts[0], shift=RIGHT*0.2), run_time=0.5)
        self.play(FadeIn(_sm_pts[1], shift=RIGHT*0.2), run_time=0.5)
        self.wait(4.9)
        self.play(FadeOut(VGroup(_sm_hd, _sm_pts)), run_time=0.5)

        # --- Outro ---
        _outro = Text('LocalLearn AI', font_size=48)
        _outro_sub = Text('Learn  ·  Visualize  ·  Understand', font_size=26)
        _outro_sub.next_to(_outro, DOWN, buff=0.3)
        self.play(Write(_outro), run_time=1.0)
        self.play(FadeIn(_outro_sub), run_time=0.8)
        self.wait(3)

